cooldown: 60
cooldown_in_creative: false
explosion_on_collision: false
tnt_timer: 80

rad_grenade:
  range_modifier: 1.2

crafts:
  grenade_tier_one:
    TNT: 1
    CANDLE: 1

  grenade_tier_two:
    TNT: 3
    CANDLE: 1

  radioactive_grenade:
    TNT: 4
    CANDLE: 1
    POISONOUS_POTATO: 1
    ROTTEN_FLESH: 2
    LINGERING_POTION: 1