name: LiteGrenades
version: 2.3
api-version: 1.21.5
main: net.swetychek.litegrenades.Main
commands:
  litegrenades:
    description: Restore config to default values
    usage: /<litegrenades> <help|give|reload|restore>