name: LiteGrenades
version: 3.21
api-version: 1.21
main: net.swetychek.litegrenades.Main
commands:
  litegrenades:
    description: Restore config to default values
    usage: /<litegrenades> <help|give|reload|restore>