name: LiteGrenades
version: 3.1
api-version: 1.21.9
main: net.swetychek.litegrenades.Main
commands:
  litegrenades:
    description: Restore config to default values
    usage: /<litegrenades> <help|give|reload|restore>